---
title: "Shannon's Demon, Made Exact (Part 1)"
subtitle: "How to make an exponential amount of money from a portfolio of almost sure losers without shorting anything"
date: 2026-07-15
categories: [quant finance, information theory, kelly criterion, risk-neutral measure, KL divergence]
bibliography: references.bib
image: shannons_demon_fiend.svg

format: 
    html:
        code-fold: true
        code-summary: "Show code"
        code-tools: true

---


### Introduction
If intuition is any guide, it shouldn't be possible for a long-only portfolio to be profitable when each of its component assets is a major loser, unless, of course, one is clairvoyant and can predict those fleeting moments when random chance will favor each asset. Yet, as I'll demonstrate in this post, not only is this possible but also an investor can (almost surely) guarantee an exponential amount of money in the long run from such a portfolio, if he knows what he's doing. It turns out that information theory provides a lovely explanation for why this is possible.


### The setup
Consider a two-asset portfolio consisting of a riskless asset and a risky asset. We will think of the riskless asset as analogous to a Swiss bank account: the account is so safe and so desirable that it pays a negative interest rate; hence, its associated gross return satisfies $r < 1.$ On the other hand, the risky asset, which I'll model as a fair coin flip, will be highly volatile in its outcome, where heads comes with a very handsome return and tails with a very steep loss. When the coin flip comes up heads, the risky asset will have a gross return of $\gamma_h$ for heads and $\gamma_t < r < \gamma_h$ for tails. In addition, I'll let $p_h$ denote the probability of heads, and I'll set $\gamma_t = \alpha / \gamma_h$, for some $\alpha > 0$. Finally, I let $f$ denote the fraction of our money that we allocate to the risky asset; hence, $1 - f$ is the fraction that we allocate to the riskless asset. Our goal is to choose $f$ intelligently so that we make as much money as possible in the long run (or lose the least possible). I'll let $S_0$ denote the initial wealth. (Obviously, $r$ must be between $\gamma_t$ and $\gamma_h$ for this game to be interesting.) 

In what follows, let $w^T = (1 - f, f)$ denote the allocation vector and $X^T = (r, \gamma)$ the random gross returns vector, where $\gamma$ takes the value $\gamma_h$ with probability $p_h$ and $\gamma_t$ with probability $1 - p_h$. Note that $w = (1,0)$ corresponds to a portfolio consisting solely of the riskless asset, and $w = (0,1)$ corresponds to a portfolio consisting solely of the risky asset. The portfolio gross return for a particular period is then given by $$Y(w) = w^T X = (1 - f)r + f\gamma,$$ so the wealth after $n$ periods is $$S_n(w) = \prod_{i=1}^n Y_i(w),$$ where $Y_i(w)$ is the portfolio gross return in period $i$.

For the specific example below, I'll set:

1. $r = 0.97$: a negative interest rate of 3% per period.
2. $\gamma_h = 2$: a 100% net gain on heads.
3. $p_h = 0.5$: it's a fair coin.
4. $\alpha = 0.8$: this implies $\gamma_t = 0.4$, i.e. a 60% net loss on tails.
5. $S_0 = 1$: initial wealth is normalized to 1.

```{python}
from coin_flip_with_riskless_asset_model import CoinFlipWithRisklessAssetModel
coin_flip_model = CoinFlipWithRisklessAssetModel(r=0.97, gamma_heads=2.0, p=0.5, alpha=0.80)
```




### The risky asset is a major loser

Obviously the riskless asset is a long-term loser, as it bleeds 3% each period. While it is less obvious, the risky asset is also a major loser, which can be seen using Monte Carlo simulations. 

```{python}
import numpy as np
from finlib.ensemble_of_returns_paths import EnsembleOfReturnsPaths
from finlib.simulating_performance import crp_performance

seed = 12345
rng = np.random.default_rng(seed)
num_paths = 10_000
num_periods = 500

weights_for_risky_asset = np.array([0.0, 1.0]) # 0% in riskless, 100% in risky
gross_returns_tensor = coin_flip_model.generate_random_gross_returns(rng, num_periods=num_periods, num_paths=num_paths)
perf_risky_matrix = crp_performance(weights_for_risky_asset, gross_returns_tensor)
ensemble_risky = EnsembleOfReturnsPaths.from_gross(perf_risky_matrix)

growth_rate_summary_df_risky = ensemble_risky.summarize_across_paths(ensemble_risky.running_growth_rate, threshold=0.0) 
wealth_summary_df_risky = ensemble_risky.summarize_across_paths(ensemble_risky.running_wealth_ratio, threshold=1.0) 
```

The figure below summarizes `{python} num_paths` simulated wealth paths over `{python} num_periods` periods (coin flips) for the risky asset, where the initial wealth is normalized to 1. The shaded region indicates the middle 95% of these wealth paths.

```{python}
#| echo: false
##### WEALTH OVER TIME (spaghetti paths), risky asset #####

import pandas as pd
from plotting_functions import create_wealth_plot
wealth_paths_risky_asset = pd.DataFrame(
    ensemble_risky.running_wealth_ratio.T,
    index=wealth_summary_df_risky.index,
)

create_wealth_plot(
    wealth_paths_risky_asset,
    wealth_summary_df_risky,
    title="Wealth over time",
)
```

Clearly the typical path through log wealth space is downward sloping in the long run (top panel). In addition, after only 100 coin flips, we see that fewer than 10% of the paths have made money, and after 250 flips, that fraction rapidly drops below 1%, and after all 500 flips, it is essentially zero (bottom panel). Indeed, the wealth path tends to zero with probability one. 

To see this, we begin with the observation that since the sequence of random variables is i.i.d., the strong law of large numbers implies that the empirical growth rate, $W_n$, converges to the expected growth rate almost surely:
$$
\begin{align}
W_n(w) &:= \frac{1}{n} \log \left(\frac{S_n(w)}{S_0}\right) \\
&= \frac{1}{n} \sum_{i=1}^n \log Y_i(w) \\
&\rightarrow \mathbb{E}\left[\log Y(w)\right] \\
&=: W(w).
\end{align}
$$
For the risky asset, we have $w^T = (0,1)$; hence, 
$$
\begin{align}
W_n(w) &\rightarrow p_h \log \gamma_h + (1 - p_h) \log \gamma_t \\
&= \frac{1}{2} \big(\log \gamma_h + \log \gamma_t \big) \\
&= \frac{1}{2} \log \alpha \\
&< 0,
\end{align}
$$
since $\alpha < 1$. Let $x$ be any number satisfying $\log \sqrt{\alpha} < x < 0$. Then, by the definition of almost sure convergence, with probability one there exists some positive integer $N$ such that for all $n > N$, we have $W_n(w) < x < 0$. This implies that $S_n(w) = e^{n W_n(w)} < e^{n x} \rightarrow 0$ with probability one, which makes rigorous the claim that the risky asset is a major loser.


The _mean_ path, however, tells a very different story. After 500 periods, the mean path sits around $10^4$, nearly 30 orders of magnitude better than the median. This is because of the small number of rare paths with enough heads to make a killing. In fact, using the binomial theorem, we see that the expected wealth after $n$ periods diverges to infinity exponentially fast:
$$
\begin{aligned}
\mathbb{E}[S_n] &= \sum_{k=0}^n {n \choose k} p_h^k (1 - p_h)^{n - k} \gamma_h^k \gamma_t^{n - k} \\
&= \big(p_h \gamma_h + (1 - p_h) \gamma_t \big)^n \\
&= \mathbb{E}[\gamma]^n \\
&= 1.2^n \\
&\rightarrow \infty.
\end{aligned}
$$
 

This enormous discrepancy makes plain one of the pitfalls of thinking solely in terms of expected value: the expected value is dominated by a small number of rare events, which are not representative of the typical outcome. In this case, the typical long-run outcome is a catastrophic loss, while the expected long-run outcome is a spectacular gain.


### How to salvage a long-only portfolio of major losers













Here is a citation! [@kelly1956]




### References

::: {#refs}
:::
